### ISSUE TITLE
defining the container

### ISSUE THREAD

**Issue by marissalerer** [zumba/angular-waypoints#10]
In Waypoints you can define the context if it's not the window. Is it possible to do that with the directive?

`var waypoint = new Waypoint({
  element: document.getElementById('context-example'),
  handler: function() {
    notify('Context example triggered')
  },
  context: document.getElementById('overflow-scroll')
})`

**Comment by young-steveo** [comment]
@marissalerer Not currently no.  This should be easy to add as a directive attribute, and pass the info along to the waypoint options hash.

Pull requests welcome.  :smile:
