### ISSUE TITLE
Only works when window is resized. I know that sounds crazy.

### ISSUE THREAD

**Issue by mcblum** [zumba/angular-waypoints#13]
Thanks for your work on this repo. We're working with it and have found that it only works (as in accurately judges the distance between the different elements and the top) after resizing the window once the page has loaded. Any idea what might be causing that?

Thank you!
Matt

**Comment by jmcguire23** [comment]
Having a similar issue. Any suggestions would be much appreciated.

**Comment by young-steveo** [comment]
@mcblum @jmcguire23 That's an interesting problem.  We're not experiencing this issue in our own projects.  Can you provide a reproduction?

**Comment by jmcguire23** [comment]
Before I create  reproduction, are you aware of nesting the waypoints directives within other directives to cause issues? Currently i have waypoint set to toggle headers at a point in the page, but this position is varying dependent on the structure and layout of the content.

**Comment by young-steveo** [comment]
@jmcguire23 We're not aware of any issues with nested waypoints.  However, be aware that events bubble in the DOM, so you'll want to stop propagation from firing your parent callbacks when the children fire.  If that doesn't help, I'll need to see a reproduction so that I can debug your issue.

**Comment by mcblum** [comment]
@young-steveo Let me enable the code that I was working with on the site and send over an example tomorrow. Is there any way to have Waypoints recalculate the positioning of the elements? I think in our case it's just an issue of the calculations being made before the page is fully loaded, and a resize fixes it because it's recalculating due to the change in window height / width.

**Comment by wudong** [comment]
I can confirm I see this issue as well, on Chrome.

**Comment by young-steveo** [comment]
@mcblum It sounds like a race condition where, as you said, the waypoints are being calculated first, then the DOM is mutated.

**Comment by mcblum** [comment]
@young-steveo Is there a way to re-calculate Waypoints? I think, even though it's sloppy, just wrapping a refresh in a timeout may take care of it until we can figure out something more sophisticated.

**Comment by young-steveo** [comment]
@mcblum You can use `Waypoint.refreshAll`:

```js
['$timeout', '$window', function($timeout, $window) {
    $timeout(function() {
        $window.Waypoint.refreshAll();
    });
}]
```

**Comment by jmcguire23** [comment]
Thanks for that, I have now successfully got this working!

Here is a stripped down version of what i have added to my App.

I am creating the assigning jQuery.noConflict(); to $ to enable the use of the jquery $() syntax within angular functions, and then running a $(window).load function and a $timeout function set to 500 which then in turn runs $window.Waypoint.refreshAll();

`  'use strict';

  var $ = jQuery.noConflict();
  
angular.module('app', [
  'zumba.angular-waypoints'
]).run(["$window", "$timeout", function($window, $timeout){
  $(window).load(function (){
    $timeout(function() {
        $window.Waypoint.refreshAll();
    }, 500);
  });
}]);`

**Comment by young-steveo** [comment]
@jmcguire23 You probably don't need the `$(window).load(function (){`

```js
angular
    .module('app', ['zumba.angular-waypoints'])
    .run(['$window', '$timeout', function($window, $timeout) {
        var Waypoint = $window.Waypoint;
        $timeout(Waypoint.refreshAll.bind(Waypoint), 500);
}]);`
```

**Comment by DrugzZ** [comment]
Hello! My issue is similar to this. On page load everything works fine but when i change paths and then return to the path with the waypoints they don't work. And when i resize the window everything works fine again. I am thinking that i can do the same thing with the refreshAll but on path change. Can you tell me how to do this?

**Comment by young-steveo** [comment]
Closing as resolved via `refreshAll`.  @mcblum let me know if it's not working for you.

**Comment by DrugzZ** [comment]
Hello! 

I have the waypoints on my homepage.

On first load (or on page refresh) everything works fine but when i change paths and after that go back to the homepage they trigger when i scroll almost to the end of the page. And when i resize the page they work normally again. I tried the refresh sollution but didn't get any positive results. 

Any ideas? 

Thank you. Your help is much appreciated.

**Comment by alexishancock** [comment]
@DrugzZ Having the same issue
