### ISSUE TITLE
Does not work with Angularjs 1.5.x

### ISSUE THREAD

**Issue by souvikbasu** [zumba/angular-waypoints#15]
The bower install fails if angularjs version installed is 1.5.x
Also I see an event only when the vertical scroll bar starts to move down and not when the scroll has reached the page end.

**Comment by young-steveo** [comment]
Unfortunately, AngularJS does not follow semver.  This lib was written when AngularJS was in version 1.3, and they have introduced breaking changes in minor versions that may or may not be compatible with our lib.

Pull requests with BC changes are welcome!

Meanwhile, I think we can update our readme to indicate the currently supported angular version.

**Comment by warapitiya** [comment]
This is a huge bug and it's not even gave me a error message.
