### ISSUE TITLE
Multiple zum-waypoints on same page, one with offset="100%"

### ISSUE THREAD

**Issue by cbaxter713** [zumba/angular-waypoints#16]
I have 2 waypoints set within 1 angular app.

The first fires as expected when that element hits the top of the viewport.

The second has an offset of 100%, but never seems to fire, whether that element hits the bottom of the viewport or the top.

Thoughts?

**Comment by young-steveo** [comment]
@cbaxter713 Thanks for the report.

I've made a few attempts to reproduce, but it seems to work for me.  Can you provide a reproduction?

**Comment by cbaxter713** [comment]
Thanks for replying.  I figured out that my second waypoint was setup outside of the angular app declaration in the DOM.  Got it fixed.  

Thanks!
