### ISSUE TITLE
Handling the wrapper of a sticky element?

### ISSUE THREAD

**Issue by GabeKagan** [zumba/angular-waypoints#19]
My organization had a long-running and difficult to track bug where a page element we'd set up as a waypoint would sometimes fail to show up when scrolling past its offset. We tracked this down to an interaction between the "sticky" waypoint features and fixed position elements in the original waypoints library (see http://imakewebthings.com/waypoints/guides/debugging/, http://imakewebthings.com/waypoints/shortcuts/sticky-elements/). As far as I can tell, you need a "wrapper" element for the waypoint element to use for actual positioning. While it's apparent how I would do this in the normal jQuery version of Waypoints, is there a similar directive in this library I can apply to the HTML waypoint element in order to get this type of functionality?

For reference, the current waypoint element (which breaks on page resizes) looks like this; I cut out the insides for brevity:

`<span zum-waypoint="waypoints" down="flags.on" up="flags.off" offset="ctrl.offset" id="scroller" ng-class="{'element-hidden': !showExtraOptions, stuck : waypoints.flags.on&&stickyExtraOptions, 'stuck-margin-left':(!loading&&!sideReadingsLoading&&waypoints.flags.on&&stickyExtraOptions)}" > </span>`

In addition, we are already using waypoints' sticky library shortcuts.

**Comment by young-steveo** [comment]
Can you put the wrapper in the markup?

```html
<span ng-class="{'element-hidden': !showExtraOptions, stuck : waypoints.flags.on&&stickyExtraOptions, 'stuck-margin-left':(!loading&&!sideReadingsLoading&&waypoints.flags.on&&stickyExtraOptions)}">
    <span zum-waypoint="waypoints" down="flags.on" up="flags.off" offset="ctrl.offset" id="scroller"></span>
</span>
```

**Comment by GabeKagan** [comment]
@young-steveo: I tried wrapping the waypoint in its ng-classes as recommended, but the behavior is the same as before - the reference position used for setting the waypoint is recalculated when I resize the browser window, causing the bug as described.

**Comment by young-steveo** [comment]
@GabeKagan Sorry, I think I got that backwards.  Try inverting it, so that the waypoint triggers wraps the fixed element.

For reference, we use this library to make our header sticky on https://www.zumba.com , and resizing the window does not seem to break it.

If that doesn't work, I would recommend writing a custom directive.
